export class IfaForeignMarginTradeRepayOrderCompleteFormModel {
  constructor() {
    this.title = '米株信用取引返済注文完了' // タイトル
    this.finishMassage = '下記の内容で注文を受け付けました。' // メッセージ（注文受付完了）
    this.brandCode = '' // 銘柄コード
    this.brandName = '' // 銘柄名称
    this.marketName = '' // 上場市場 市場略名
    this.tradeCd = '' // 取引種別
    this.lastTradeDate = '' // 返済期限
    this.orderQuantity = '' // 数量
    this.repayPositionDesignateMethod = '' // 返済建玉指定方法
    this.repaySelectOrder = '' // 返済選択順序
    this.orderPriceKindList = '' // 価格条件
    this.limitPrice = '' // 指値注文単価
    this.limitPrice2 = '' // 指値注文単価_通貨
    this.stopOrderPrice = '' // 逆指値発火条件価格
    this.stopOrderPriceText2 = '' // 逆指値発火条件
    this.stopOrderExecutePrice2 = '' // 逆指値注文単価
    this.stopOrderExecutePriceText1 = '' // 逆指値成行
    this.periodRadio = '' // 期間条件
    this.period = '' // 期間
    this.foreignDepositTypeRadio = '' // 預り区分
    this.kessaiHoho = '' // 決済方法
    this.orderDate = '' // 国内注文日時
    this.businessDaysAfterOrder = '' // 国内約定予定日
    this.kanyuKbn = '' // 勧誘区分
    this.jutyuKbn = '' // 受注方法
    this.checkInsider = '' // インサイダー確認
    this.tradeNoticeInfoBrandMsg = '' // 取引注意情報（銘柄）確認
    this.tradingCautionInformation = '' // 取引注意情報（銘柄）確認 【初期値】空白
    this.noticeInfoAlert = '' // 注意情報アラート確認
    this.noticeInfoAlertConfirm = '' // 注意情報アラート確認 【初期値】空白
    this.noticeAlert = '' // お知らせアラート確認
    this.notificationAlertConfirm = '' // お知らせアラート確認 【初期値】空白
    this.immediateStopOrder = '' // 逆指値注文即時発火確認 【初期値】空白
    this.stopOrderInstantMessage = '' // 逆指値注文即時発火
    this.nextDayCheck = '' // 翌営業日向け注文確認 【初期値】空白
    this.nextBusinessDayMessage = '' // 翌営業日向け注文
    this.orderNumber = '' // 注文番号
    this.orderSubNumber = '' // 注文Sub番号
    this.brandInformation = '' // 銘柄情報
    this.marketInfo = [] // 市場情報
    this.tradeKbn = '' // 売買区分
    this.autoBuyingClassification = '' // 自動買付区分
    this.trailStopWidth = '' // トレールストップ幅
    this.executeBasePrice = '' // 成行基準価格
    this.settlementCurrencyCode = '' // 決済通貨
    this.fxRate = '' // 為替レート
    this.averageTradePrice = '' // 平均約定単価
    this.unTradeQuantity = '' // 未約定数量
    this.tradeQuantityTotal = '' // 約定数量（合計）
    this.contractAmountForeign = '' // 約定金額（外貨）
    this.contractAmount = '' // 約定金額（円貨）
    this.foreignDeliveryAmount = '' // 受渡金額（外貨）
    this.yenTransitAmount = '' // 受渡金額（円貨）
    this.contractDeliveryAmount = '' // 受渡金額（約定分）
    this.domesticCommForeign = '' //　国内手数料（外貨）
    this.domesticCommJpAmount = '' //　国内手数料（円貨）
    this.domesticConsumptionTaxJpAmount = '' //　国内消費税（外貨）
    this.yenDomesticTax = '' //　国内消費税（円貨）
    this.localCommForeign = '' //　現地手数料等（外貨）
    this.localCommJpAmount = '' //　現地手数料等（円貨）
    this.localSettlementForeign = '' //　現地精算金額（外貨）
    this.localSettlementJpAmount = '' //　現地精算金額（円貨）
    this.nisaRestraintAmount = '' //　NISA枠拘束金額
    this.approximateCapitalGainsTax = '' //　概算譲渡益税
    this.orderStatus = '' //　注文状況
    this.tradeStatus = '' //　約定状況
    this.stopOrderStatus = '' //　発火状況
    this.domesticSettlementDate = '' // 国内受渡日
    this.localTradeDate = '' // 現地約定日
    this.foreignSettlementDate = '' // 現地受渡日
    this.tradeDateTime = '' // 約定日時
    this.expiredDateTime = '' // 失効日時
    this.stockTradeType = '' // 株取引区分
    this.marginDueDate = '' // 信用期日
    this.settlement = '' // 決済損益
    this.depositDeficientAmount = '' // 保証金不足金額
    this.transferDepositAmount = '' // 振替預り金額
    this.transferSecurityValuation = '' // 振替有価証券評価額
    this.quotePrice = '' // 見積価格 【初期値】空白
    this.approximateCostTotal = '' // 概算諸経費合計
    this.marginPositionPowerOrderAfter = '' // 信用建余力（注文後）
    this.marginDepositRateOrderAfter = '' // 委託保証金率（注文後預託率）
    this.brandClass = '' // 銘柄種別
    this.tradeLimitTitle = '' // 注意銘柄
    this.tradeLimitUrl = '' // 本日の注意銘柄
  }
}
