export class IfaForeignMarginTradeRepayOrderConfirmFormModel {
  constructor() {
    this.title = '米株信用取引返済注文確認' // タイトル
    this.tradeCd = '' // 取引種別
    this.marketCode = '' // 市場情報.市場コード
    this.marketName = '' // 市場情報.市場略名
    this.brandCode = '' // 銘柄コード
    this.brandName = '' // 銘柄情報.銘柄名
    this.orderQuantity = '' // 注文数量 【初期値】0
    this.orderPriceKindList = '' // 価格条件
    this.limitPrice = '' // 注文単価
    this.stopOrderPrice = '' // 逆指値発火条件価格 【初期値】0
    this.executeBasePrice = '' // 成行基準価格
    this.periodRadio = '' // 期間条件 【初期値】空白
    this.period = '' // 期間 【初期値】空白
    this.depositType = '' // 預り区分 【初期値】空白
    this.kessaiHoho = '' // 決済方法 【初期値】空白
    this.kanyuKbn = '' // 勧誘区分 【初期値】空白
    this.jutyuKbn = '' // 受注方法 【初期値】空白
    this.lastTradeDate = '' // 返済期限
    this.repayPositionDesignateMethod = '' // 返済建玉指定方法
    this.repaySelectOrder = '' // 返済選択順序
    this.trade = '' // 建区分
    this.domesticTradeDate = '' // 国内新規約定日
    this.foreignTradeDate = '' // 現地新規約定日
    this.unitPrice = '' // 建単価
    this.stockTicket = '' // 株価チケット
    this.checkInsider = '' // インサイダー確認 【初期値】空白
    this.tradingCautionInformation = [] // 取引注意情報（銘柄）確認 【初期値】空白
    this.noteInfoCheckbox = [] // 注意情報アラート確認 【初期値】空白
    this.noteLimitCheck = [] // お知らせアラート確認 【初期値】空白
    this.methodCheck = [] // 逆指値注文即時発火確認 【初期値】空白
    this.nextDayCheck = [] // 翌営業日向け注文確認 【初期値】空白
    this.noticeInfoAlert = [] // 注意情報アラート
    this.noticeAlert = [] // お知らせアラート
    this.methodCheckMessage = [] // 逆指値注文即時発火メッセージ
    this.nextBusinessDayMessage = [] // 現地約定日超過メッセージ
    this.tradeNoticeInfoBrandMsg = [] // 取引注意情報（銘柄）メッセージ
    this.tradeLimitUrl = '本日の注意銘柄' // 本日の注意銘柄
    this.orderNumber = '' // 注文番号
    this.orderSubNumber = '' // 注文Sub番号
    this.tradeKbn = '' // 売買区分
    this.currencyCode = '' // 取引通貨
    this.orderDate = '' // 注文日時
    this.tradeLimitTitle = '' // 注意銘柄見出し
    this.customerNameKanji = '' // 顧客名（漢字）
    this.customerNameKana = '' // 顧客名（カナ）
    this.butenCode = '' // 部店
    this.accountNumber = '' // 口座番号
    this.listedMarket = '' // 上場市場
    this.priceBasicInfo = {} // 価格基本情報
    this.hiddenOrderPrice = '' // 指値注文単価 【初期値】0
    this.currency = '' // 指値注文単価_通貨
    this.stopOrderPriceText2 = '' // 逆指値発火条件
    this.stopOrderExecutePrice2 = '' // 逆指値注文単価 【初期値】0
    this.stopOrderExecutePriceText1 = '' // 逆指値成行
    this.domesticSettlementDate = '' // 国内受渡予定日 【初期値】"----/--/--"
    this.quotePrice = '' // 見積価格 【初期値】空白
    this.contractAmountForeign = '' // 概算約定代金 【初期値】空白
    this.approximateCost = '' // 概算諸経費等 【初期値】空白
    this.settlement = '' // 概算損益金 【初期値】空白
    this.brandCode276 = '' // 銘柄名称
    this.marginDueDate = '' // 信用期日
    this.insiderConfirmCheckBox = '' // 確認項目.インサイダー確認
    this.autoPurchaseClassification = '' // 自動買付区分
    this.trailStopWidth = '' // トレールストップ幅
    this.settlementCurrencyCode = '' // 決済通貨
    this.fxRate = '' // 為替レート
    this.averageTradePrice = '' // 平均約定単価
    this.unTradeQuantity = '' // 未約定数量
    this.tradeQuantityTotal = '' // 約定数量（合計）
    this.contractAmount = '' // 約定金額（円貨）
    this.foreignDeliveryAmount = '' // 受渡金額（外貨）
    this.yenDeliveryAmount = '' // 受渡金額（円貨）
    this.contractDeliveryAmount = '' // 受渡金額（約定分）
    this.domesticCommForeign = '' //　国内手数料（外貨）
    this.domesticCommJpAmount = '' //　国内手数料（円貨）
    this.domesticConsumptionTaxForeign = '' //　国内消費税（外貨）
    this.domesticConsumptionTaxJpAmount = '' //　国内消費税（円貨）
    this.localCommForeign = '' //　現地手数料等（外貨）
    this.localCommJpAmount = '' //　現地手数料等（円貨）
    this.localSettlementForeign = '' //　現地精算金額（外貨）
    this.localSettlementJpAmount = '' //　現地精算金額（円貨）
    this.nisaRestraintAmount = '' //　NISA枠拘束金額
    this.approximateCapitalGainsTax = '' //　概算譲渡益税
    this.orderStatus = '' //　注文状況
    this.tradeStatus = '' //　約定状況
    this.stopOrderStatus = '' //　発火状況
    this.localTradeDate = '' // 現地約定日
    this.foreignSettlementDate = '' // 現地受渡日
    this.businessDaysAfterOrder = '' // 約定日時
    this.expiredDateTime = '' // 失効日時
    this.stockTradeType = '' // 株取引区分
    this.depositDeficientAmount = '' // 保証金不足金額
    this.transferDepositAmount = '' // 振替預り金額
    this.transferSecurityValuation = '' // 振替有価証券評価額
    this.marginPositionPowerOrderAfter = '' // 信用建余力（注文後）
    this.marginDepositRateOrderAfter = '' // 委託保証金率（注文後預託率）
    this.tradeLimitTitle = '' // 注意銘柄
    this.countryCode = '' // 国コード(追加)
    this.brandSyubetsu = '' // 銘柄種別
    this.stopOrderPriceKindList = '' // 価格条件(逆指値)
    this.closedDayUrl = '' // 休場日URL
    this.yenClosedUrl = '' // 円貨決済停止日URL
    this.usequityListUrl = '' // 取扱銘柄一覧URL
    this.tradingAttentionUrl = '' // お取引注意事項URL
    this.newMainSiteParamList = [] // 新メインサイト用パラメータ
    this.linkUrl = '' // リンクURL
    this.postRequest = {} // POSTリクエスト
  }
}
