export class IfaForeignMarginTradeRepayOrderInputFormModel {
  constructor() {
    this.title = '米株信用取引返済注文入力'
    this.settlementOrderAbleQuantityMsg = '返済可能な建玉がありません。' // メッセージ（決済注文可能数量0）
    this.brandCode = '' // 銘柄コード
    this.tradeCd = '' // 取引種別
    this.paymentDeadline = '' // 弁済期限
    this.depositType = '' // 預り区分
    this.trade = '' // 建区分
    this.repayPositionDesignateMethod = '1' // 返済建玉指定方法 【初期値】一括指定
    this.marketCode = '' // 市場コード
    this.closeOrderQuantity = '' // 返済株数 【初期値】空欄（アクション定義書では注文数量）
    this.tradingUnit = ''
    this.total = '' // 合計
    this.orderPriceKindList = '' // 価格条件 【初期値】空欄
    this.limitPrice2 = '' // 注文単価（指値） 【初期値】空欄
    this.stopOrderExecutePrice2 = '' // 注文単価（逆指値） 【初期値】空欄
    this.stopOrderPrice = '' // 発火条件価格（逆指値） 【初期値】空欄
    this.stopOrderPriceKindList = '' // 価格条件（逆指値）【初期値】未選択
    this.periodRadio = null // 期間条件 【初期値】未選択
    this.period = '' // 期間（日付指定） 【初期値】未選択
    this.kessaiHoho = '2' // 決済方法
    this.repaySelectOrder = '0' // 返済順序 【初期値】評価益順
    this.kanyuKbn = '' // 勧誘区分 【初期値】空欄
    this.jutyuKbn = '' // 受注方法 【初期値】空欄
    this.stockTicket = '' // 株価チケット
    this.previousDayValue = '' // 建単価(個別)
    this.quantity = '' // 数量
    this.checkInsider = [] // インサイダー確認 【初期値】未選択
    this.tradeLimitUrl = ''
    this.closedDayUrl = ''
    this.yenClosedUrl = ''
    this.usequityListUrl = ''
    this.tradingAttentionUrl = ''
    this.selectAbleDepositTypeList = [] // 選択可能預り区分リスト
    this.selectAbleSettlementMethodList = [] // 選択可能決済方法リスト
    this.selectAblePriceTermsList = [] // 選択可能価格条件リスト
    this.selectAbleMarginDueDateList = [] // 選択可能信用期日リスト
    this.selectAbleRepayPositionDesignationMethodList = [] // 選択可能返済建玉指定方法リスト
    this.selectAbleRepaySelectSequenceList = [] // 選択可能返済選択順序リスト
    this.selectAblePeriodTermsList = [] // 選択可能期間条件リスト
    this.validityPeriodList = [] // 有効期間一覧
    this.marketAbbreviatedName = '' // 市場情報.市場略名（市場名）
    this.countryCode = '' // 国コード(追加)
    this.currencyCode = '' // 取引通貨(追加)
    this.timeZoneAbbreviatedName = '' // タイムゾーン略名
    this.brandListedStatus = '' // 銘柄上場ステータス
    this.tradeLowerLimitQuantity = '' // 取引下限数量
    this.tradeUpperLimitQuantity = '' // 取引上限数量
    this.brandClass = '' // 銘柄種別
    this.tradeLimitTitle = '' // 注意銘柄
    this.brandName = '' // 銘柄名称
    this.listedMarket = '' // 上場市場
    this.tradeUnit = '' // 取引単位 【初期値】未選択
    this.stopOrderExecutePriceText1 = '' // 注文単価（逆指値）
    this.priceBasicInfo = {} // 価格基本情報
    this.foreignStockMarginPositionSummary = {} // 外国株式信用建玉サマリ
    this.foreignStockMarginPositionDetailList = [] // 外国株式信用建玉明細一覧
    this.newMainSiteParamList = [] // 新メインサイト用パラメータ
    this.linkUrl = '' // リンクURL
    this.postRequest = {} // POSTリクエスト
  }
}
