export class IfaDomesticStockOrderCorrectConfirmFormModel {
  constructor() {
    this.title = {
      id: 'SUB0202_0208-03_2',
      name: '国内株式注文訂正確認'
    }
    this.customerNameKanji = '' // 顧客名（漢字）
    this.customerNameKana = '' // 顧客名（カナ）
    this.butenCode = '' // 部店
    this.accountNumber = '' // 口座番号
    this.brandCode = '' // 銘柄コード
    this.brandName = '' // 銘柄名
    this.beforeCorrectOrderType = '' // 注文種別（訂正前）
    this.orderKind = '' // 注文種別（訂正後）
    this.beforeCorrectTradeType = '' // 取引種別（訂正前）
    this.tradeCd = '' // 取引種別（訂正後）
    this.market = '' // 市場（訂正前）
    this.afterCorrectMarket = '' // 市場（訂正後）
    this.beforeCorrectUnTradeQuantity = '' // 未約定数量（訂正前）
    this.unTradeQuantity = '' // 未約定数量（訂正後）
    this.beforeCorrectOrderQuantity = '' // 受注数量（訂正前）
    this.quantity = '' // 受注数量（訂正後）
    this.beforeCorrectPriceSasinariHouhou = '' // 執行方法
    this.beforeCorrectPriceSasinariJyouken = '' // 執行条件（指値）
    this.beforeCorrectPricePrice = '' // 注文単価（指値）
    this.sasinariJyouken = '' // 執行条件（指値）
    this.price = '' // 注文単価（指値）
    this.correctBeforePriceMarketExecutionConditionText = '' // 執行条件（成行）
    this.marketExecutionConditionText = '' // 執行条件（成行）
    this.correctBeforePriceStopOrderPriceText1 = '' // 発火条件価格（逆指値）前文言
    this.beforeCorrectPriceTriggerPrice = '' // 発火条件価格（逆指値）
    this.beforeCorrectPriceStopOrderPriceText2 = '' // 発火条件価格（逆指値）後文言
    this.correctBeforePriceStopOrderLimitExecutionConditionText = '' // 執行条件（逆指値/指値）
    this.correctBeforePriceDomesticCorrectStopLimitOrderPrice = '' // 注文単価（逆指値/指値）
    this.correctBeforePriceStopOrderMarketExecutionConditionText = '' // 執行条件（逆指値/成行）
    this.correctBeforePriceStopOrderExecutePriceText2 = '' // 注文単価（逆指値）文言
    this.stopOrderPriceText1 = '' // 発火条件価格（逆指値）前文言
    this.triggerPrice = '' // 発火条件価格（逆指値）
    this.stopOrderPriceText2 = '' // 発火条件価格（逆指値）後文言
    this.stopOrderLimitExecutionConditionText = '' // 執行条件（逆指値/指値）
    this.domesticCorrectStopLimitOrderPrice = '' // 注文単価（逆指値/指値）
    this.stopOrderMarketExecutionConditionText = '' // 執行条件（逆指値/成行）
    this.stopOrderExecutePriceText2 = '' // 注文単価（逆指値）文言
    this.period = '' // 注文期間（訂正前）
    this.afterCorrectOrderPeriod = '' // 注文期間（訂正後）
    this.beforeCorrectDeposit = '' // 預り区分（訂正前）
    this.depositType = '' // 預り区分（訂正後）
    this.beforeCorrectCommType = '' // 手数料区分（訂正前）
    this.tesuuryouKbn = '' // 手数料区分（訂正後）
    this.beforeCorrectPriceOco1SasinariHouhou = '' // 執行方法
    this.beforeCorrectPriceOco1SasinariJyouken = '' // 執行条件
    this.beforeCorrectPriceOco1Price = '' // 注文単価
    this.oco1SasinariHouhou = '' // 執行方法
    this.oco1SasinariJyouken = '' // 執行条件
    this.oco1Price = '' // 注文単価
    this.correctBeforePriceOco2StopOrderPriceText1 = '' // 発火条件価格（逆指値）前文言
    this.beforeCorrectPriceOco2TriggerPrice = '' // 発火条件価格（逆指値）
    this.beforeCorrectPriceOco2StopOrderPriceText2 = '' // 発火条件価格（逆指値）後文言
    this.correctBeforePriceLimitExecutionConditionText = '' // 執行条件（OCO1）
    this.beforeCorrectPriceOco2Price = '' // 注文単価（逆指値/指値）
    this.beforeCorrectPriceOco2GyakusasiHouhou = '' // 執行条件（逆指値/成行）
    this.correctBeforePriceCorrectStopOrderExecutePriceText = '' // 注文単価（逆指値）文言
    this.oco2StopOrderPriceText1 = '' // 発火条件価格（逆指値）前文言
    this.oco2TriggerPrice = '' // 発火条件価格（逆指値）
    this.oco2StopOrderPriceText2 = '' // 発火条件価格（逆指値）後文言
    this.limitExecutionConditionText = '' // 執行条件（OCO1）
    this.oco2Price = '' // 注文単価（逆指値/指値）
    this.oco2GyakusasiHouhou = '' // 執行条件（逆指値/成行）
    this.correctStopOrderExecutePriceText = '' // 注文単価（逆指値）文言
    this.ifd2BeforeCorrectTradeType = '' // 取引種別（訂正前）
    this.ifd2TradeCd = '' // 取引種別（訂正後）
    this.ifd2BeforeCorrectUnTradeQuantity = '' // 未約定数量（訂正前）
    this.ifd2UnTradeQuantity = '' // 未約定数量（訂正後）
    this.ifd2BeforeCorrectOrderQuantity = '' // 受注数量（訂正前）
    this.ifd2OrderAmount = '' // 受注数量（訂正後）
    this.afterCorrecBuyPower = '' // 訂正後買付余力
    this.nisaInvestableQuoteLabel = '' // NISA投資可能枠（ラベル）
    this.nisaInvestableQuote = '' // NISA投資可能枠
    this.contractDate = '' // 約定予定日
    this.deliveryDate = '' // 受渡予定日
    this.orderDayTime = '' // 受注日時
    this.kanyuKbn = '' // 勧誘区分
    this.receiveOrderType = '' // 受注方法
    this.checkInsider = '' // インサイダー確認
    this.checkSor = '' // SOR確認
    this.tradingCautionInformation = '0' // 取引注意情報（銘柄）確認 【初期値】未確認
    this.chkBoxLabel = '' // コンプラランクチェック確認見出し
    this.invitationCheck = '0' // コンプラランクチェック確認 【初期値】未確認
    this.noticeInfoAlertCheck = '0' // 注意情報アラート確認 【初期値】未確認
    this.noticeAlertCheck = '0' // お知らせアラート確認 【初期値】未確認
    this.ecOrderNo = '' // EC受注番号
    this.doneState = '' // DONE状態
    this.rbeOrderStatus = '' // RBE注文ステータス
    this.workingStatus = '' // 発火状態
    this.orderDate = '' // 受注日
    this.correctSorOrderClassification = '' // 訂正SOR注文区分
    this.correctSorOrderResultClassification = '' // 訂正SOR注文結果区分
    this.fundComplianceCheck = '' // コンプラランクチェック.コンプラチェック用資金性格

    this.beforeCorrectPrice = []
  }
}
