export class IfaStockDetailInfoFormModel {
  constructor() {
    this.title = '株式詳細情報' // 画面名
    this.brandCode = '' // 銘柄コード
    this.brandName = '' // 銘柄名
    this.market = '' // 市場
    this.onedayCreditBuyCategory = '' // 一日信用買建区分
    this.onedayCreditSellCategory = '' // 一日信用売建区分
    this.premiumShortSaleCcategory = '' // プレミアム空売り区分
    this.updateTime = '' // 更新日時
    this.currentPrice = '-' // 現在値 【初期値】"-"
    this.tick = ' ' // 現在値ティック 【初期値】"△"（半角スペース）
    this.currentFlag = ' ' // 現在値フラグ 【初期値】"△"（半角スペース）
    this.diff = '-' // 前日比 【初期値】"-"
    this.ratio = '（-%）' // 前日比率（％） 【初期値】"（-%）"
    this.updateDate = '（--/--/--' // 更新日付 【初期値】"（--/--/--"
    this.updateTime4 = ' --:--）' // 更新時刻 【初期値】" --:--）"
    this.start = '-' // 始値 【初期値】"-"
    this.startTime = '（--:--）' // 始値時刻 【初期値】"（--:--）"
    this.high = '' // 高値 【初期値】"-"
    this.highTime = '（--:--）' // 高値時刻 【初期値】"（--:--）"
    this.low = '' // 安値 【初期値】"-"
    this.lowTime = '（--:--）' // 安値時刻 【初期値】"（--:--）"
    this.last = '' // 前日終値 【初期値】"-"
    this.lastDate = '（--/--/--）' // 前日終値日付 【初期値】" （--/--/--）"
    this.volume = '' // 出来高 【初期値】"-"
    this.buySellPrice = '-(千円)' // 売買代金 【初期値】"-(千円)"
    this.executionSellOrderQuantity = '' // 成行売注文数量
    this.sellSignVolumeOver = '-' // 売気配株数 【初期値】"-"
    this.sellSignVolume10 = '-' // 売気配株数 【初期値】"-"
    this.sellSignVolume9 = '-' // 売気配株数 【初期値】"-"
    this.sellSignVolume8 = '-' // 売気配株数 【初期値】"-"
    this.sellSignVolume7 = '-' // 売気配株数 【初期値】"-"
    this.sellSignVolume6 = '-' // 売気配株数 【初期値】"-"
    this.sellSignVolume5 = '-' // 売気配株数 【初期値】"-"
    this.sellSignVolume4 = '-' // 売気配株数 【初期値】"-"
    this.sellSignVolume3 = '-' // 売気配株数 【初期値】"-"
    this.sellSignVolume2 = '-' // 売気配株数 【初期値】"-"
    this.sellSignVolume1 = '-' // 売気配株数 【初期値】"-"
    this.sellSignPriceFlg = '-' // 売気配値フラグ 【初期値】"-"
    this.sellSignPrice10 = '-' // 売気配値 【初期値】"-"
    this.sellSignPrice9 = '-' // 売気配値 【初期値】"-"
    this.sellSignPrice8 = '-' // 売気配値 【初期値】"-"
    this.sellSignPrice7 = '-' // 売気配値 【初期値】"-"
    this.sellSignPrice6 = '-' // 売気配値 【初期値】"-"
    this.sellSignPrice5 = '-' // 売気配値 【初期値】"-"
    this.sellSignPrice4 = '-' // 売気配値 【初期値】"-"
    this.sellSignPrice3 = '-' // 売気配値 【初期値】"-"
    this.sellSignPrice2 = '-' // 売気配値 【初期値】"-"
    this.sellSignPrice1 = '-' // 売気配値 【初期値】"-"
    this.buySignPrice1 = '-' // 買気配値 【初期値】"-"
    this.buySignPrice2 = '-' // 買気配値 【初期値】"-"
    this.buySignPrice3 = '-' // 買気配値 【初期値】"-"
    this.buySignPrice4 = '-' // 買気配値 【初期値】"-"
    this.buySignPrice5 = '-' // 買気配値 【初期値】"-"
    this.buySignPrice6 = '-' // 買気配値 【初期値】"-"
    this.buySignPrice7 = '-' // 買気配値 【初期値】"-"
    this.buySignPrice8 = '-' // 買気配値 【初期値】"-"
    this.buySignPrice9 = '-' // 買気配値 【初期値】"-"
    this.buySignPrice10 = '-' // 買気配値 【初期値】"-"
    this.buySignPriceFlg = '-' // 買気配値フラグ 【初期値】"-"
    this.executionBuyOrderQuantity = '-' // 成行買注文数量
    this.buySignVolume1 = '-' // 買気配株数 【初期値】"-"
    this.buySignVolume2 = '-' // 買気配株数 【初期値】"-"
    this.buySignVolume3 = '-' // 買気配株数 【初期値】"-"
    this.buySignVolume4 = '-' // 買気配株数 【初期値】"-"
    this.buySignVolume5 = '-' // 買気配株数 【初期値】"-"
    this.buySignVolume6 = '-' // 買気配株数 【初期値】"-"
    this.buySignVolume7 = '-' // 買気配株数 【初期値】"-"
    this.buySignVolume8 = '-' // 買気配株数 【初期値】"-"
    this.buySignVolume9 = '-' // 買気配株数 【初期値】"-"
    this.buySignVolume10 = '-' // 買気配株数 【初期値】"-"
    this.buySignVolumeUnder = '-' // 買気配株数 【初期値】"-"
    this.yearToDateHigh = '-' // 年初来高値 【初期値】"-"
    this.yearToDateLow = '-' // 年初来安値 【初期値】"-"
    this.marginSellBalance = '-' // 信用売残 【初期値】"-"
    this.creditSellWeekDiff = '-' // 信用売残前週比 【初期値】"-"
    this.creditBuyStock = '-' // 信用買残 【初期値】"-"
    this.creditBuyWeekDiff = '-' // 信用買残前週比 【初期値】"-"
    this.loanMagnification = '-' // 貸借倍率 【初期値】"-倍"
    this.creditLoan = '-' // 信用貸借 【初期値】"-"
  }
}
