export class IfaBbApplyCorrectCancelInputFormModel {
  constructor() {
    this.brand = '' // 銘柄表示
    this.unit = '' // 申込単位 【初期値】""
    this.assumeCondition = '' // 仮条件 【初期値】""
    this.bbPresentationFromTo = '' // BB申込期間 【初期値】""
    this.bbLotDate = '' // 抽選日 【初期値】""
    this.butenCode = '' // 部店
    this.accountNumber = '' // 口座番号
    this.customerNameKanji = '' // 顧客名
    this.openAcctDate = '' // 口座開設年月日
    this.investmentPolicyTypeName = '' // 投資方針
    this.discretionAlloCount = '' // 本年の年間裁量配分割当回数
    this.professionName = '' // 職業
    this.stockSpotInvestExperienceYears = '' // 投資経験年数(株式現物)
    this.discretionAllocateAbleTimes = '' // 本年の年間裁量配分可能回数
    this.officeName = '' // 勤務先名
    this.financialAssetsTypeName = '' // 金融資産
    this.yenBuyingPower = '' // 買付余力
    this.complianceRank = '' // コンプラランク
    this.depositAssetAmount = '' // 預り資産額
    this.edelivAgreementDate = '' // 電子交付同意
    this.readTime = '' // 目論見書閲覧
    this.bbVolume = '' // 数量
    this.bbCreateDate = '' // 申込日時
    this.marketOrder = '' // 成行
    this.priceDiscountRate = [] // 価格/ディスカント率
    this.bbInvestorAttName = [] // 投資家属性
    this.corporationWarningMessage = '' // ※法人の場合は必ず変更してください。
    this.discretionQuantity = '' // 裁量希望数量
    this.discretionSelectReasonList = '' // 裁量選定理由
    this.kanyuKbn = [] // 勧誘区分 【初期値】未選択
    this.correctWarningMessage = '' // ※訂正時は必ず選択してください。
    this.receiveOrderType = [] // 受注方法 【初期値】未選択
    this.warningMessage = '' // ※訂正時は必ず選択してください。
    this.bbRemark = '' // 備考
    this.brandCode = '' // 銘柄コード
    this.bookBuildingPresentationFrom = '' // ブックビルディング申込期間（開始）
    this.corporationType = '' // 法人区分
    this.financialAssetsType = '' // 金融資産区分
    this.brandName = '' // 銘柄名
    this.sellBuyUnitType = '' // 売買単位区分
    this.bbBrandIssuePriceTypeValue = '' // 発行価格区分
    this.customerNameKanji = '' // 顧客名（漢字）
    this.customerNameKana = '' // 顧客名（カナ）
    this.beforeCorrectQuantity = '' // 訂正前数量
    this.beforeCorrectMarketOrder = '' // 訂正前成行
    this.beforeCorrectPrice = '' // 訂正前価格
    this.beforeCorrectDiscountRate = '' // 訂正前ディスカント率
    this.beforeCorrectInvestorAttributeValue = '' // 訂正前投資家属性順序
    this.beforeCorrectInvestorAttributeName = '' // 訂正前投資家属性名
    this.beforeCorrectDiscretionQuantity = '' // 訂正前裁量希望数量
    this.beforeCorrectDiscretionSelectReason = '' // 訂正前裁量選定理由
    this.beforeCorrectBbRemark = '' // 訂正前備考
    this.periodUpdateMessage = '' // 期間変更メッセージ
    this.priceUpdateMessage = '' // 価格変更メッセージ
    this.customerCode = ''
  }
}
