<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ifa-portal-gw</artifactId>
    <packaging>jar</packaging>

    <name>ifa-portal-gw</name>
    <description>gateway for ifa-portal-webapp</description>

    <parent>
        <groupId>com.sbisec</groupId>
        <artifactId>ifa-portal-web</artifactId>
        <version>1.0.8</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <dependencies>
        <!-- ifa-portal-common -->
        <dependency>
            <groupId>com.sbisec</groupId>
            <artifactId>ifa-portal-common</artifactId>
            <version>${project.version}</version>
        </dependency>

        <!-- Apache POI -->
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi</artifactId>
            <version>5.4.1</version>
        </dependency>
        <dependency>
            <groupId>org.apache.poi</groupId>
            <artifactId>poi-ooxml</artifactId>
            <version>5.4.1</version>
        </dependency>

        <!-- IBM ICU -->
        <dependency>
            <groupId>com.ibm.icu</groupId>
            <artifactId>icu4j</artifactId>
            <version>69.1</version>
        </dependency>

        <!-- Java JWT -->
        <dependency>
            <groupId>com.auth0</groupId>
            <artifactId>java-jwt</artifactId>
            <version>4.4.0</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>ifa-portal-gw</finalName>
        <resources>
            <resource>
                <directory>src/main/resources</directory>
                <filtering>true</filtering>
            </resource>
        </resources>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <excludes>
                        <!-- テストツールの本番リリース除外設定 -->
                        <exclude>com/sbisec/helios/common/testtool/**</exclude>
                        <exclude>com/sbisec/helios/common/unittest/**</exclude>
                        <exclude>com/sbisec/helios/gw/testtool/**</exclude>
                        <exclude>com/sbisec/helios/ap/testtool/**</exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>