export class IfaMarginNewOrderInputFormModel {
  constructor() {
    this.title = '信用新規注文入力'
    this.stopOrderPriceText1 = '現在値が'
    this.stopOrderPriceText2 = 'になった時点で'
    this.stopOrderExecutePriceText2 = 'で執行'
    this.domesticStopOrderPriceText1 = 'になった時点でOCO1注文を以下の執行条件に訂正'
    this.market = '' // 市場
    this.brandCode = '' // 銘柄コード
    this.brandName = '' // 銘柄名
    this.regKbn = '' // 規制銘柄区分
    this.settlementDateT0 = '' // 新規建余力（T+0）［ラベル］
    this.settlementDateT1 = '' // 新規建余力（T+1）［ラベル］
    this.newBuildingCapacityT0 = '' // 新規建余力（T+0）
    this.newBuildingCapacityT1 = '' // 新規建余力（T+1）
    this.maintenanceRateJpyAmountDescriptionMessage = '' // 維持率(円貨)説明文言
    this.rateT0 = '' // 維持率（T+0）
    this.rateT1 = '' // 維持率（T+1）
    this.orderKind = '1' // 注文種別 【初期値】通常/逆指値
    this.tradeCd = '' // 取引種別
    this.orderQuantity = '' // 数量 【初期値】空欄
    this.sasinariHouhou = '1' // 執行方法 【初期値】指値
    this.unit = '' // 売買単位 【初期値】項目を非表示
    this.sasinariJyouken = ' ' // 執行条件（指値） 【初期値】条件なし
    this.priceBuyLimitLow = '' // 制限値幅（指値）安
    this.priceBuyLimitHigh = '' // 制限値幅（指値）高
    this.priceSellLimitLow = '' // 制限値幅（指値）安
    this.priceSellLimitHigh = '' // 制限値幅（指値）高
    this.priceLimitDate = '' // 制限値幅（指値）日付
    this.triggerPrice = '' // 発火条件価格（逆指値）
    this.gyakusasiHouhou = '1' // 執行方法（逆指値） 【初期値】指値
    this.stopOrderMarketExecutionConditionList = '6' // 執行条件（逆指値/成行） 【初期値】条件なし
    this.price = '' // 注文単価
    this.marginTradeTypeText = '' // 信用取引区分
    this.priceLimitStopOrder = '' // 制限値幅（逆指値）
    this.stopOrderPriceLimitDate = '' // 制限値幅（逆指値）日付
    this.warningMessage = '' // 注意喚起文言
    this.businessDay = '' // 営業日
    this.businessDayList = [] // 営業日リスト
    this.periodRadio = null // 期間 【初期値】未選択
    this.limit = '' // 期間(日付)
    this.mktIppanLoanKbnTky = '' // 信用取引区分 東証
    this.mktIppanLoanKbnNgy = '' // 信用取引区分 名証
    this.mktIppanLoanKbnFko = '' // 信用取引区分 福証
    this.mktIppanLoanKbnSpr = '' // 信用取引区分 札証
    this.oco1Price = '' // OCO1注文単価
    this.oco1SasinariJyouken = ' ' // OCO1執行条件（逆指値/成行） 【初期値】条件なし
    this.oco1OrderExecuteMethodList = '1' // OCO1執行方法 【初期値】指値
    this.oco1LimitExecutionConditionList = '' // OCO1執行条件（指値）
    this.oco1DomesticLimitPrice = '' // OCO1注文単価（指値）
    this.oco2OrderExecuteMethodList = '1' // OCO2執行方法 【初期値】指値
    this.oco2Price = '' // OCO2注文単価 【初期値】空欄
    this.oco2TriggerPrice = '' // OCO2発火条件価格（逆指値）
    this.oco2DomesticStopOrderPrice = '' // OCO2発火条件価格（逆指値）
    this.oco2StopOrderExecuteMethodList = '1' // OCO2 執行方法（逆指値）
    this.oco2StopOrderMarketExecutionConditionList = ' ' // OCO2執行条件（逆指値/成行）
    this.oco2DomesticLimitPrice = '' // OCO2注文単価
    this.ifd1SasinariJyouken = ' ' // IFD1執行条件（逆指値/成行） 【初期値】条件なし
    this.ifd1OrderExecuteMethodList = '1' // IFD1執行方法 【初期値】指値
    this.ifd1LimitExecutionConditionList = '' // IFD1執行条件（指値）
    this.ifd1DomesticStopOrderPrice = '' // IFD1発火条件価格（逆指値）
    this.ifd1StopOrderExecuteMethodList = '' // IFD1 執行方法（逆指値）
    this.ifd1DomesticLimitPrice = '' // IFD1注文単価
    this.ifd2SasinariJyouken = ' ' // IFD2執行条件（逆指値/成行） 【初期値】条件なし
    this.ifd2PeriodRadio = null // IFD2.期間.期間条件
    this.ifd2Limit = '' // IFD2.期間.日付（当日中も格納）
    this.ifd2OrderExecuteMethodList = '1' // IFD2執行方法 【初期値】指値
    this.ifd2LimitExecutionConditionList = '' // IFD2執行条件（指値）
    this.ifd2DomesticStopOrderPrice = '' // IFD2発火条件価格（逆指値）
    this.ifd2StopOrderExecuteMethodList = '1' // IFD2 執行方法（逆指値）
    this.ifd2DomesticLimitPrice = '' // IFD2注文単価（指値）
    this.tradingCoursText = '' // 手数料区分
    this.solicitTypeName = '' // 勧誘区分
    this.kanyuKbn = '' // 勧誘区分
    this.receiveOrderType = '' // 受注方法
    this.checkInsider = [] // 確認項目.インサイダー確認
    this.checkSor = [] // 確認項目.SOR確認
    this.mktLoanKbnPts = '' // PTS貸借区分
    this.mktIppanLoanKbnPts = '' // PTS一般信用区分
    this.mktLoanKbnTky = '' // 東証貸借区分
  }
}
