export class IfaMarginNewOrderCancelConfirmFormModel {
  constructor() {
    this.title = {
      id: 'SUB0202_0212-03_1',
      name: '信用新規注文取消確認'
    }
    /** 銘柄コード（半角英数字）. */
    this.brandCode = ''
    /** 銘柄名（全角半角）. */
    this.brandName = ''
    /** 市場（全角）. */
    this.market = ''
    /** 取引種別（全角半角）. */
    this.tradeCd = ''
    /** 注文数量. */
    this.orderQuantity = ''
    /** 未約定数量（数値(整数)）. */
    this.unTradeQuantity = ''
    /** 期間. */
    this.period = ''
    /** 預り区分（全角半角）. */
    this.depositType = ''
    /** 注文種別（半角英数字）. */
    this.orderKind = ''
    /** 受注日時. */
    this.orderDayTime = ''
    /** 通常/逆指値.執行方法. */
    this.sasinariHouhou = ''
    /** 通常/逆指値.執行条件. */
    this.sasinariJyouken = ''
    /** 通常/逆指値.発火条件価格（逆指値）（数値(小数)）. */
    this.triggerPrice = ''
    /** 通常/逆指値.発火条件価格（逆指値）ゾーン. */
    this.triggerPriceZone = ''
    /** 通常/逆指値.執行方法（逆指値）. */
    this.gyakusasiHouhou = ''
    /** 通常/逆指値.注文単価（数値(小数)）. */
    this.price = ''
    /** OCO1.執行方法. */
    this.oco1SasinariHouhou = ''
    /** OCO1.執行条件. */
    this.oco1SasinariJyouken = ''
    /** OCO1.注文単価（数値(小数)）. */
    this.oco1Price = ''
    /** OCO2.発火条件価格（逆指値）（数値(小数)）. */
    this.oco2TriggerPrice = ''
    /** OCO2.発火条件価格（逆指値）ゾーン. */
    this.oco2TriggerPriceZone = ''
    /** OCO2.執行方法（逆指値）. */
    this.oco2GyakusasiHouhou = ''
    /** OCO2.執行条件（逆指値）. */
    this.oco2GyakusasiJyouken = ''
    /** OCO2.注文単価（数値(小数)）. */
    this.oco2Price = ''
    /** IFD1.執行方法. */
    this.ifd1SasinariHouhou = ''
    /** IFD1.執行条件. */
    this.ifd1SasinariJyouken = ''
    /** IFD1.発火条件価格（逆指値）（数値(小数)）. */
    this.ifd1TriggerPrice = ''
    /** IFD1.発火条件価格（逆指値）ゾーン. */
    this.ifd1TriggerPriceZone = ''
    /** IFD1.執行方法（逆指値）. */
    this.ifd1GyakusasiHouhou = ''
    /** IFD1.注文単価（数値(小数)）. */
    this.ifd1Price = ''
    /** IFD2.期間.日付. */
    this.ifd2Limit = ''
    /** IFD2.執行方法. */
    this.ifd2SasinariHouhou = ''
    /** IFD2.執行条件. */
    this.ifd2SasinariJyouken = ''
    /** IFD2.発火条件価格（逆指値）（数値(小数)）. */
    this.ifd2TriggerPrice = ''
    /** IFD2.発火条件価格（逆指値）ゾーン. */
    this.ifd2TriggerPriceZone = ''
    /** IFD2.執行方法（逆指値）. */
    this.ifd2GyakusasiHouhou = ''
    /** IFD2.注文単価（数値(小数)）. */
    this.ifd2Price = ''
    /** 発火状態（半角英数字）. */
    this.workingStatus = ''
    /** 弁済期限（全角半角）. */
    this.paymentDeadline = ''
    /** 信用取引区分（算出）. */
    this.marginTradeTypeTextCalculation = ''
    /** 自動注文種別（半角英数字）. */
    this.autoOrderClass = ''
    /** RBE注文種別（全角半角）. */
    this.rbeChumonShubetsu = ''
    /** 指成区分（半角英数字）. */
    this.sashinariKbn = ''
    /** 指値（数値(小数)）. */
    this.sashine = ''
    /** トリガ発動ゾーン（半角英数字）. */
    this.triggerZone = ''
    /** トリガ値段（数値(小数)）. */
    this.triggerNedan = ''
    /** OCO指成区分（半角英数字）. */
    this.ocoSasinariKbn = ''
    /** OCO指値（数値(小数)）. */
    this.ocoSashine = ''
    /** DONE指成区分（半角英数字）. */
    this.doneSasinariKbn = ''
    /** DONE指値（数値(小数)）. */
    this.doneSashine = ''
    /** DONERBE注文種別（全角半角）. */
    this.doneRbeOrderKind = ''
    /** DONEトリガ発動ゾーン（半角英数字）. */
    this.doneTriggerZone = ''
    /** DONEトリガ値段（数値(小数)）. */
    this.doneTriggerNedan = ''
    /** DONEOCO指成区分（半角英数字）. */
    this.doneOcoSasinariKbn = ''
    /** DONEOCO指値（数値(小数)）. */
    this.doneOcoSashine = ''
    /** DONE有効期限（全角半角）. */
    this.doneYuukouKigen = ''
    /** RBE注文ステータス（半角英数字）. */
    this.rbeOrderStatus = ''
    /** EC受注番号（半角英数字）. */
    this.ecOrderNo = ''
    /** 弁済期限年月日数. */
    this.paymentDeadlineDate = ''
    /** 年月日区分. */
    this.dateKbn = ''
    /** 手数料区分（採用）（半角英数字）. */
    this.comIdR = ''
  }
}
