export class IfaMarginNewOrderConfirmFormModel {
  constructor() {
    this.title = '信用新規注文確認'
    this.warnMessage = '注文はまだ完了していません。画面下の注文発注ボタンを押下してください。'
    this.shubetu = '' // 種別
    this.butenCode = '' // 部店
    this.brandName = '' // 銘柄名
    this.market = '' // 市場
    this.regKbn = '' // 規制銘柄区分
    this.tradeNoticeInfoBrandMsg = [] // 取引注意情報メッセージ
    this.noticeInfoAlert = [] // アラートメッセージ
    this.noticeAlert = [] // お知らせメッセージ
    this.insiderErrorMsg = [] // 内部者確認メッセージ
    this.insiderKbn = '' // 取引承認対象区分
    this.shortSellingRegulationConflictMessage = [] // 空売り規制抵触メッセージ
    this.code = '' // エラーコード
    this.errMessage = '' // エラーメッセージ
    this.quoteUnitPrice = '' // 見積単価
    this.contractAmount = '' // 約定金額
    this.charge = '' // 手数料/諸費用
    this.consumptionTax = '' // 消費税
    this.applicableInterestRate = '' // 適用金利
    this.applicableStockLendingFees = '' // 適用貸株料
    this.settlementAmount = '' // 精算金額
    this.contractDate = '' // 約定予定日
    this.deliveryDate = '' // 受渡予定日
    this.orderDayTime = '' // 受注日時
    this.brandCode = '' // 銘柄コード（半角英数字）
    this.tradeCd = '' // 取引種別
    this.orderQuantity = '' // 注文数量
    this.periodRadio = '' // 期間期間条件
    this.limit = '' // 期間日付
    this.orderKind = '' // 注文種別
    this.sasinariHouhou = '' // 通常/逆指値執行方法
    this.sasinariJyouken = '' // 通常/逆指値執行条件
    this.triggerPrice = '' // 通常/逆指値発火条件価格
    this.gyakusasiHouhou = '' // 通常/逆指値執行方法（逆指値）
    this.price = '' // 通常/逆指値注文単価
    this.marginTradeTypeText = '' // 信用取引区分
    this.oco1OrderExecuteMethodList = '' // OCO1執行方法
    this.oco1LimitExecutionConditionList = '' // OCO1執行条件
    this.oco1DomesticLimitPrice = '' // OCO1注文単価
    this.oco2DomesticStopOrderPrice = '' // OCO2発火条件価格
    this.oco2StopOrderExecuteMethodList = '' // OCO2執行方法
    this.oco2StopOrderMarketExecutionConditionList = '' // OCO2執行条件
    this.oco2DomesticLimitPrice = '' // OCO2注文単価
    this.ifd1OrderExecuteMethodList = '' // IFD1執行方法
    this.ifd1LimitExecutionConditionList = '' // IFD1執行条件
    this.ifd1DomesticStopOrderPrice = '' // IFD1発火条件価格
    this.ifd1StopOrderExecuteMethodList = '' // IFD1執行方法
    this.ifd1DomesticLimitPrice = '' // IFD1注文単価
    this.ifd2PeriodRadio = '' // IFD2期間期間条件
    this.ifd2Limit = '' // IFD2期間日付
    this.ifd2OrderExecuteMethodList = '' // IFD2執行方法
    this.ifd2LimitExecutionConditionList = '' // IFD2執行条件
    this.ifd2DomesticStopOrderPrice = '' // IFD2発火条件価格
    this.ifd2StopOrderExecuteMethodList = '' // IFD2執行方法
    this.ifd2DomesticLimitPrice = '' // IFD2注文単価
    this.customerAttributeName = '' // 契約締結前交付書面コード名(顧客情報から取得)
    this.kanyuKbn = '' // 勧誘区分
    this.receiveOrderType = '' // 受注方法
    this.checkInsider = '' // インサイダー確認
    this.checkSor = '' // SOR確認
    this.tradingCautionInformation = '' // 取引注意情報（銘柄）確認
    this.noteInfoCheckbox = '' // 注意情報アラート確認
    this.noteLimitCheck = '' // お知らせアラート確認
    this.insiderErrorConfirmationCheckbox = '' // 内部者エラー確認 【初期値】未確認
    this.shortSellingRegulationsCheckbox = '' // 空売り規制の抵触確認
    this.premiumShortSaleCcategory = '' // プレミアム空売り区分
    this.orderedMarket = '' // 注文入力市場
  }
}
