// Generated by delombok at Wed Dec 15 13:30:13 JST 2021
package com.sbisec.helios.ap.common.util;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;

public class Crypt {
	@JsonCreator
	Crypt(@JsonProperty("key") String key, @JsonProperty("iv") String iv) {
		this.key = key;
		this.iv = iv;
	}

	String key;
	String iv;

	@java.lang.SuppressWarnings("all")
	public String getKey() {
		return this.key;
	}

	@java.lang.SuppressWarnings("all")
	public String getIv() {
		return this.iv;
	}
}
