#=====================================================
# ifa-portal-ap Properties
#=====================================================
#FileDownloadUtil
A5_SIZE_TO=233
B5_SIZE_TO=277
A4_SIZE_TO=330
B4_SIZE_TO=392
