<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ifa-portal-common</artifactId>
    <packaging>jar</packaging>

    <name>ifa-portal-common</name>
    <description>common for ifa-portal-webapp</description>

    <parent>
        <groupId>com.sbisec</groupId>
        <artifactId>ifa-portal-web</artifactId>
        <version>1.0.8</version>
        <relativePath>../pom.xml</relativePath>
    </parent>

    <dependencies>
        <!-- jakarta -->
        <dependency>
            <groupId>jakarta.servlet</groupId>
            <artifactId>jakarta.servlet-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <!-- Security -->
        <dependency>
            <groupId>jakarta.annotation</groupId>
            <artifactId>jakarta.annotation-api</artifactId>
            <scope>provided</scope>
        </dependency>

        <dependency>
            <groupId>pcenter-cli</groupId>
            <artifactId>pcenter-cli-yanap</artifactId>
            <version>2.1.3</version>
        </dependency>

        <!-- Bean Validation API -->
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
        </dependency>

        <!-- IBM ICU -->
        <dependency>
            <groupId>com.ibm.icu</groupId>
            <artifactId>icu4j</artifactId>
            <version>69.1</version>
        </dependency>

        <!-- OkHttp -->
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.12.0</version>
        </dependency>
    </dependencies>

    <build>
        <finalName>ifa-portal-common</finalName>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <configuration>
                    <excludes>
                        <!-- テストツールの本番リリース除外設定 -->
                        <exclude>com/sbisec/helios/**/testtool/**</exclude>
                        <exclude>com/sbisec/helios/**/unittest/**</exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
