// Generated by BRPC 0.8.0

package com.sbisec.helios.ap.common.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/** NRI_QueryFund response header and outdata */
@JsonIgnoreProperties(ignoreUnknown = true)
public class QueryFundOut {

  @lombok.Getter(onMethod = @__(@JsonProperty("header")))
  @lombok.Setter(onMethod = @__(@JsonProperty("header")))
  private ResponseHeader header;

  @lombok.Getter(onMethod = @__(@JsonProperty("outdata")))
  @lombok.Setter(onMethod = @__(@JsonProperty("outdata")))
  private QueryFundOutData outdata;

  public QueryFundOut(ResponseHeader header, QueryFundOutData outdata) {
    this.header = header;
    this.outdata = outdata;
  }

  public QueryFundOut() {}
}
