// Generated by BRPC 0.8.0

package com.sbisec.helios.ap.common.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/** query_fund */
@JsonIgnoreProperties(ignoreUnknown = true)
public class QueryFund {

  @lombok.Getter(onMethod = @__(@JsonProperty("kyokai_code")))
  @lombok.Setter(onMethod = @__(@JsonProperty("kyokai_code")))
  private String kyokaiCode;

  @lombok.Getter(onMethod = @__(@JsonProperty("fund_type")))
  @lombok.Setter(onMethod = @__(@JsonProperty("fund_type")))
  private String fundType;

  @lombok.Getter(onMethod = @__(@JsonProperty("fund_code_ser_no")))
  @lombok.Setter(onMethod = @__(@JsonProperty("fund_code_ser_no")))
  private String fundCodeSerNo;

  @lombok.Getter(onMethod = @__(@JsonProperty("fund_code_sub")))
  @lombok.Setter(onMethod = @__(@JsonProperty("fund_code_sub")))
  private String fundCodeSub;

  @lombok.Getter(onMethod = @__(@JsonProperty("fund_closed_time")))
  @lombok.Setter(onMethod = @__(@JsonProperty("fund_closed_time")))
  private String fundClosedTime;

  @lombok.Getter(onMethod = @__(@JsonProperty("sec_name")))
  @lombok.Setter(onMethod = @__(@JsonProperty("sec_name")))
  private String secName;

  @lombok.Getter(onMethod = @__(@JsonProperty("itaku_kasya_name")))
  @lombok.Setter(onMethod = @__(@JsonProperty("itaku_kasya_name")))
  private String itakuKasyaName;

  @lombok.Getter(onMethod = @__(@JsonProperty("mrt_order_date")))
  @lombok.Setter(onMethod = @__(@JsonProperty("mrt_order_date")))
  private String mrtOrderDate;

  @lombok.Getter(onMethod = @__(@JsonProperty("trade_date")))
  @lombok.Setter(onMethod = @__(@JsonProperty("trade_date")))
  private String tradeDate;

  @lombok.Getter(onMethod = @__(@JsonProperty("yugu_ritsu_bunsi")))
  @lombok.Setter(onMethod = @__(@JsonProperty("yugu_ritsu_bunsi")))
  private String yuguRitsuBunsi;

  @lombok.Getter(onMethod = @__(@JsonProperty("yugu_ritsu_bunbo")))
  @lombok.Setter(onMethod = @__(@JsonProperty("yugu_ritsu_bunbo")))
  private String yuguRitsuBunbo;

  @lombok.Getter(onMethod = @__(@JsonProperty("prospectus_request_date")))
  @lombok.Setter(onMethod = @__(@JsonProperty("prospectus_request_date")))
  private String prospectusRequestDate;

  @lombok.Getter(onMethod = @__(@JsonProperty("prospectus_send_date")))
  @lombok.Setter(onMethod = @__(@JsonProperty("prospectus_send_date")))
  private String prospectusSendDate;

  @lombok.Getter(onMethod = @__(@JsonProperty("buy_date")))
  @lombok.Setter(onMethod = @__(@JsonProperty("buy_date")))
  private String buyDate;

  @lombok.Getter(onMethod = @__(@JsonProperty("stop_order_flag")))
  @lombok.Setter(onMethod = @__(@JsonProperty("stop_order_flag")))
  private String stopOrderFlag;

  @lombok.Getter(onMethod = @__(@JsonProperty("trade_status")))
  @lombok.Setter(onMethod = @__(@JsonProperty("trade_status")))
  private String tradeStatus;

  @lombok.Getter(onMethod = @__(@JsonProperty("switch_id")))
  @lombok.Setter(onMethod = @__(@JsonProperty("switch_id")))
  private String switchId;

  public QueryFund(
      String kyokaiCode,
      String fundType,
      String fundCodeSerNo,
      String fundCodeSub,
      String fundClosedTime,
      String secName,
      String itakuKasyaName,
      String mrtOrderDate,
      String tradeDate,
      String yuguRitsuBunsi,
      String yuguRitsuBunbo,
      String prospectusRequestDate,
      String prospectusSendDate,
      String buyDate,
      String stopOrderFlag,
      String tradeStatus,
      String switchId) {
    this.kyokaiCode = kyokaiCode;
    this.fundType = fundType;
    this.fundCodeSerNo = fundCodeSerNo;
    this.fundCodeSub = fundCodeSub;
    this.fundClosedTime = fundClosedTime;
    this.secName = secName;
    this.itakuKasyaName = itakuKasyaName;
    this.mrtOrderDate = mrtOrderDate;
    this.tradeDate = tradeDate;
    this.yuguRitsuBunsi = yuguRitsuBunsi;
    this.yuguRitsuBunbo = yuguRitsuBunbo;
    this.prospectusRequestDate = prospectusRequestDate;
    this.prospectusSendDate = prospectusSendDate;
    this.buyDate = buyDate;
    this.stopOrderFlag = stopOrderFlag;
    this.tradeStatus = tradeStatus;
    this.switchId = switchId;
  }

  public QueryFund() {}
}
