// Generated by BRPC 0.8.0

package com.sbisec.helios.ap.common.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/** NRI_QueryFund request header and indata */
@JsonIgnoreProperties(ignoreUnknown = true)
public class QueryFundIn {

    @lombok.Getter(onMethod = @__(@JsonProperty("header")))
    @lombok.Setter(onMethod = @__(@JsonProperty("header")))
    private RequestHeader header;

    @lombok.Getter(onMethod = @__(@JsonProperty("indata")))
    @lombok.Setter(onMethod = @__(@JsonProperty("indata")))
    private QueryFundInData indata;

    public QueryFundIn(RequestHeader header, QueryFundInData indata) {
      this.header = header;
      this.indata = indata;
    }

    public QueryFundIn() {}
}
