// Generated by BRPC 0.8.0

package com.sbisec.helios.ap.common.dto;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/** NRI_QueryFund indata */
@JsonIgnoreProperties(ignoreUnknown = true)
public class QueryFundInData {

  @lombok.Getter(onMethod = @__(@JsonProperty("buten_cd")))
  @lombok.Setter(onMethod = @__(@JsonProperty("buten_cd")))
  private String butenCd;

  @lombok.Getter(onMethod = @__(@JsonProperty("koza_no")))
  @lombok.Setter(onMethod = @__(@JsonProperty("koza_no")))
  private String kozaNo;

  @lombok.Getter(onMethod = @__(@JsonProperty("asset_management_id")))
  @lombok.Setter(onMethod = @__(@JsonProperty("asset_management_id")))
  private String assetManagementId;

  @lombok.Getter(onMethod = @__(@JsonProperty("ref_from")))
  @lombok.Setter(onMethod = @__(@JsonProperty("ref_from")))
  private String refFrom;

  @lombok.Getter(onMethod = @__(@JsonProperty("ref_to")))
  @lombok.Setter(onMethod = @__(@JsonProperty("ref_to")))
  private String refTo;

  @lombok.Getter(onMethod = @__(@JsonProperty("account_get_kbn")))
  @lombok.Setter(onMethod = @__(@JsonProperty("account_get_kbn")))
  private String accountGetKbn;

  public QueryFundInData(
      String butenCd,
      String kozaNo,
      String assetManagementId,
      String refFrom,
      String refTo,
      String accountGetKbn) {
    this.butenCd = butenCd;
    this.kozaNo = kozaNo;
    this.assetManagementId = assetManagementId;
    this.refFrom = refFrom;
    this.refTo = refTo;
    this.accountGetKbn = accountGetKbn;
  }

  public QueryFundInData() {}
}
