// Generated by BRPC 0.8.0

package com.sbisec.helios.ap.common.dto;

import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonProperty;

/** NRI_QueryFund outdata */
@JsonIgnoreProperties(ignoreUnknown = true)
public class QueryFundOutData {

  @lombok.Getter(onMethod = @__(@JsonProperty("date")))
  @lombok.Setter(onMethod = @__(@JsonProperty("date")))
  private String date;

  @lombok.Getter(onMethod = @__(@JsonProperty("time")))
  @lombok.Setter(onMethod = @__(@JsonProperty("time")))
  private String time;

  @lombok.Getter(onMethod = @__(@JsonProperty("shubetu")))
  @lombok.Setter(onMethod = @__(@JsonProperty("shubetu")))
  private String shubetu;

  @lombok.Getter(onMethod = @__(@JsonProperty("code")))
  @lombok.Setter(onMethod = @__(@JsonProperty("code")))
  private String code;

  @lombok.Getter(onMethod = @__(@JsonProperty("message")))
  @lombok.Setter(onMethod = @__(@JsonProperty("message")))
  private String message;

  @lombok.Getter(onMethod = @__(@JsonProperty("office_code")))
  @lombok.Setter(onMethod = @__(@JsonProperty("office_code")))
  private String officeCode;

  @lombok.Getter(onMethod = @__(@JsonProperty("account_no")))
  @lombok.Setter(onMethod = @__(@JsonProperty("account_no")))
  private String accountNo;

  @lombok.Getter(onMethod = @__(@JsonProperty("t_date")))
  @lombok.Setter(onMethod = @__(@JsonProperty("t_date")))
  private String tDate;

  @lombok.Getter(onMethod = @__(@JsonProperty("treatment_price1")))
  @lombok.Setter(onMethod = @__(@JsonProperty("treatment_price1")))
  private String treatmentPrice1;

  @lombok.Getter(onMethod = @__(@JsonProperty("treatment_price2")))
  @lombok.Setter(onMethod = @__(@JsonProperty("treatment_price2")))
  private String treatmentPrice2;

  @lombok.Getter(onMethod = @__(@JsonProperty("jrnisa_treatment_price1")))
  @lombok.Setter(onMethod = @__(@JsonProperty("jrnisa_treatment_price1")))
  private String jrnisaTreatmentPrice1;

  @lombok.Getter(onMethod = @__(@JsonProperty("jrnisa_treatment_price2")))
  @lombok.Setter(onMethod = @__(@JsonProperty("jrnisa_treatment_price2")))
  private String jrnisaTreatmentPrice2;

  @lombok.Getter(onMethod = @__(@JsonProperty("total_number")))
  @lombok.Setter(onMethod = @__(@JsonProperty("total_number")))
  private String totalNumber;

  @lombok.Getter(onMethod = @__(@JsonProperty("hit_number")))
  @lombok.Setter(onMethod = @__(@JsonProperty("hit_number")))
  private String hitNumber;

  @lombok.Getter(onMethod = @__(@JsonProperty("query_fund")))
  @lombok.Setter(onMethod = @__(@JsonProperty("query_fund")))
  private List<QueryFund> queryFund;

  public QueryFundOutData(
      String date,
      String time,
      String shubetu,
      String code,
      String message,
      String officeCode,
      String accountNo,
      String tDate,
      String treatmentPrice1,
      String treatmentPrice2,
      String jrnisaTreatmentPrice1,
      String jrnisaTreatmentPrice2,
      String totalNumber,
      String hitNumber,
      List<QueryFund> queryFund) {
    this.date = date;
    this.time = time;
    this.shubetu = shubetu;
    this.code = code;
    this.message = message;
    this.officeCode = officeCode;
    this.accountNo = accountNo;
    this.tDate = tDate;
    this.treatmentPrice1 = treatmentPrice1;
    this.treatmentPrice2 = treatmentPrice2;
    this.jrnisaTreatmentPrice1 = jrnisaTreatmentPrice1;
    this.jrnisaTreatmentPrice2 = jrnisaTreatmentPrice2;
    this.totalNumber = totalNumber;
    this.hitNumber = hitNumber;
    this.queryFund = queryFund;
  }

  public QueryFundOutData() {}
}
