package com.sbisec.helios.ap.api.athena.enums;

import org.springframework.util.ObjectUtils;

/**
 * 
 * @Description:国コード
 * @author shuchen.xin
 * @date: 06/04/2021
 */
public enum CountryCode {

    AD("AD", "Andorra.", "アンドラ"),
    AE("AE", "United Arab Emirates (the).", "アラブ首長国連邦"),
    AF("AF", "Afghanistan.", "アフガニスタン・イスラム共和国"),
    AG("AG", "Antigua and Barbuda.", "アンティグア・バーブーダ"),
    AI("AI", "Anguilla.", "イギリス領アンギラ"),
    AL("AL", "Albania.", "アルバニア共和国"),
    AM("AM", "Armenia.", "アルメニア共和国"),
    AO("AO", "Angola.", "アンゴラ共和国"),
    AQ("AQ", "Antarctica.", "南極大陸"),
    AR("AR", "Argentina.", "アルゼンチン共和国"),
    AS("AS", "American Samoa.", "アメリカ領サモア"),
    AT("AT", "Austria.", "オーストリア共和国"),
    AU("AU", "Australia.", "オーストラリア連邦"),
    AW("AW", "Aruba.", "オランダ領アルバ"),
    AX("AX", "Åland Islands.", "フィンランド領オーランド諸島"),
    AZ("AZ", "Azerbaijan.", "アゼルバイジャン共和国"),
    BA("BA", "Bosnia and Herzegovina.", "ボスニア・ヘルツェゴビナ"),
    BB("BB", "Barbados.", "バルバドス"),
    BD("BD", "Bangladesh.", "バングラデシュ人民共和国"),
    BE("BE", "Belgium.", "ベルギー王国"),
    BF("BF", "Burkina Faso.", "ブルキナファソ"),
    BG("BG", "Bulgaria.", "ブルガリア共和国"),
    BH("BH", "Bahrain.", "バーレーン王国"),
    BI("BI", "Burundi.", "ブルンジ共和国"),
    BJ("BJ", "Benin.", "ベナン共和国"),
    BL("BL", "Saint Barthélemy.", "フランス領サン・バルテルミー"),
    BM("BM", "Bermuda.", "イギリス領バミューダ諸島"),
    BN("BN", "Brunei Darussalam.", "ブルネイ・ダルサラーム国"),
    BO("BO", "Bolivia (Plurinational State of).", "ボリビア多民族国"),
    BQ("BQ", "Bonaire, Sint Eustatius and Saba.", "オランダ領ボネール、シント・ユースタティウスおよびサバ"),
    BR("BR", "Brazil.", "ブラジル連邦共和国"),
    BS("BS", "Bahamas (the).", "バハマ共同体"),
    BT("BT", "Bhutan.", "ブータン王国"),
    BV("BV", "Bouvet Island.", "ブーベ島（ノルウェー領）"),
    BW("BW", "Botswana.", "ボツワナ共和国"),
    BY("BY", "Belarus.", "ベラルーシ共和国"),
    BZ("BZ", "Belize.", "ベリーズ"),
    CA("CA", "Canada.", "カナダ"),
    CC("CC", "Cocos (Keeling) Islands (the).", "オーストラリア領ココス（キーリング）諸島"),
    CD("CD", "Congo (the Democratic Republic of the).", "コンゴ民主共和国"),
    CF("CF", "Central African Republic (the).", "中央アフリカ共和国"),
    CG("CG", "Congo (the).", "コンゴ共和国"),
    CH("CH", "Switzerland.", "スイス連邦"),
    CI("CI", "Côte d'Ivoire.", "コートジボワール共和国"),
    CK("CK", "Cook Islands (the).", "ニュージーランド領クック諸島"),
    CL("CL", "Chile.", "チリ共和国"),
    CM("CM", "Cameroon.", "カメルーン共和国"),
    CN("CN", "China.", "中華人民共和国"),
    CO("CO", "Colombia.", "コロンビア共和国"),
    CR("CR", "Costa Rica.", "コスタリカ共和国"),
    CU("CU", "Cuba.", "キューバ共和国"),
    CV("CV", "Cabo Verde.", "カーボベルデ共和国"),
    CW("CW", "Curaçao.", "オランダ領キュラソー"),
    CX("CX", "Christmas Island.", "オーストラリア領クリスマス島"),
    CY("CY", "Cyprus.", "キプロス共和国"),
    CZ("CZ", "Czechia.", "チェコ共和国"),
    DE("DE", "Germany.", "ドイツ連邦共和国"),
    DJ("DJ", "Djibouti.", "ジブチ共和国"),
    DK("DK", "Denmark.", "デンマーク王国"),
    DM("DM", "Dominica.", "ドミニカ国"),
    DO("DO", "Dominican Republic (the).", "ドミニカ共和国"),
    DZ("DZ", "Algeria.", "アルジェリア民主人民共和国"),
    EC("EC", "Ecuador.", "エクアドル共和国"),
    EE("EE", "Estonia.", "エストニア共和国"),
    EG("EG", "Egypt.", "エジプト・アラブ共和国"),
    EH("EH", "Western Sahara*.", "西サハラ*"),
    ER("ER", "Eritrea.", "エリトリア国"),
    ES("ES", "Spain.", "スペイン王国"),
    ET("ET", "Ethiopia.", "エチオピア連邦民主共和国"),
    EU("EU", "European Union.", "欧州連合"),
    FI("FI", "Finland.", "フィンランド共和国"),
    FJ("FJ", "Fiji.", "フィジー共和国"),
    FK("FK", "Falkland Islands (the) [Malvinas].", "イギリス領フォークランド諸島（マルビナス）"),
    FM("FM", "Micronesia (Federated States of).", "ミクロネシア連邦"),
    FO("FO", "Faroe Islands (the).", "デンマーク領フェロー諸島"),
    FR("FR", "France.", "フランス共和国"),
    GA("GA", "Gabon.", "ガボン共和国"),
    GB("GB", "United Kingdom of Great Britain and Northern Ireland (the).", "グレートブリテンおよび北アイルランド連合王国"),
    GD("GD", "Grenada.", "グレナダ"),
    GE("GE", "Georgia.", "グルジア"),
    GF("GF", "French Guiana.", "フランス領ギアナ"),
    GG("GG", "Guernsey.", "イギリス領ガーンジー"),
    GH("GH", "Ghana.", "ガーナ共和国"),
    GI("GI", "Gibraltar.", "イギリス領ジブラルタル"),
    GL("GL", "Greenland.", "デンマーク領グリーンランド"),
    GM("GM", "Gambia (the).", "ガンビア共和国"),
    GN("GN", "Guinea.", "ギニア共和国"),
    GP("GP", "Guadeloupe.", "フランス領グアドループ"),
    GQ("GQ", "Equatorial Guinea.", "赤道ギニア共和国"),
    GR("GR", "Greece.", "ギリシャ共和国"),
    GS("GS", "South Georgia and the South Sandwich Islands.", "イギリス領サウスジョージア・サウスサンドウィッチ諸島"),
    GT("GT", "Guatemala.", "グアテマラ共和国"),
    GU("GU", "Guam.", "アメリカ合衆国グアム"),
    GW("GW", "Guinea-Bissau.", "ギニアビサウ共和国"),
    GY("GY", "Guyana.", "ガイアナ共和国"),
    HK("HK", "Hong Kong.", "香港"),
    HM("HM", "Heard Island and McDonald Islands.", "オーストラリア領ハード島とマクドナルド諸島"),
    HN("HN", "Honduras.", "ホンジュラス共和国"),
    HR("HR", "Croatia.", "クロアチア共和国"),
    HT("HT", "Haiti.", "ハイチ共和国"),
    HU("HU", "Hungary.", "ハンガリー"),
    ID("ID", "Indonesia.", "インドネシア共和国"),
    IE("IE", "Ireland.", "アイルランド"),
    IL("IL", "Israel.", "イスラエル国"),
    IM("IM", "Isle of Man.", "イギリス領マン島"),
    IN("IN", "India.", "インド共和国"),
    IO("IO", "British Indian Ocean Territory (the).", "イギリス領インド洋地域"),
    IQ("IQ", "Iraq.", "イラク共和国"),
    IR("IR", "Iran (Islamic Republic of).", "イラン・イスラム共和国"),
    IS("IS", "Iceland.", "アイスランド共和国"),
    IT("IT", "Italy.", "イタリア共和国"),
    JE("JE", "Jersey.", "イギリス領ジャージー"),
    JM("JM", "Jamaica.", "ジャマイカ"),
    JO("JO", "Jordan.", "ヨルダン・ハシェミット王国"),
    JP("JP", "Japan.", "国内"),
    KE("KE", "Kenya.", "ケニア共和国"),
    KG("KG", "Kyrgyzstan.", "キルギス共和国"),
    KH("KH", "Cambodia.", "カンボジア王国"),
    KI("KI", "Kiribati.", "キリバス共和国"),
    KM("KM", "Comoros (the).", "コモロ連合"),
    KN("KN", "Saint Kitts and Nevis.", "セントクリストファー・ネイビス連邦"),
    KP("KP", "Korea (the Democratic People's Republic of).", "朝鮮民主主義人民共和国"),
    KR("KR", "Korea (the Republic of).", "大韓民国"),
    KW("KW", "Kuwait.", "クウェート国"),
    KY("KY", "Cayman Islands (the).", "イギリス領ケイマン諸島"),
    KZ("KZ", "Kazakhstan.", "カザフスタン共和国"),
    LA("LA", "Lao People's Democratic Republic (the).", "ラオス人民民主共和国"),
    LB("LB", "Lebanon.", "レバノン共和国"),
    LC("LC", "Saint Lucia.", "セントルシア"),
    LI("LI", "Liechtenstein.", "リヒテンシュタイン公国"),
    LK("LK", "Sri Lanka.", "スリランカ民主社会主義共和国"),
    LR("LR", "Liberia.", "リベリア共和国"),
    LS("LS", "Lesotho.", "レソト王国"),
    LT("LT", "Lithuania.", "リトアニア共和国"),
    LU("LU", "Luxembourg.", "ルクセンブルク大公国"),
    LV("LV", "Latvia.", "ラトビア共和国"),
    LY("LY", "Libya.", "リビア国"),
    MA("MA", "Morocco.", "モロッコ王国"),
    MC("MC", "Monaco.", "モナコ公国"),
    MD("MD", "Moldova (the Republic of).", "モルドバ共和国"),
    ME("ME", "Montenegro.", "モンテネグロ"),
    MF("MF", "Saint Martin (French part).", "フランス領サン・マルタン"),
    MG("MG", "Madagascar.", "マダガスカル共和国"),
    MH("MH", "Marshall Islands (the).", "マーシャル諸島共和国"),
    MK("MK", "North Macedonia.", "北マケドニア共和国"),
    ML("ML", "Mali.", "マリ共和国"),
    MM("MM", "Myanmar.", "ミャンマー連邦共和国"),
    MN("MN", "Mongolia.", "モンゴル国"),
    MO("MO", "Macao.", "中華人民共和国マカオ特別行政区"),
    MP("MP", "Northern Mariana Islands (the).", "アメリカ合衆国北マリアナ諸島"),
    MQ("MQ", "Martinique.", "フランス領マルティニーク"),
    MR("MR", "Mauritania.", "モーリタニア・イスラム共和国"),
    MS("MS", "Montserrat.", "イギリス領モントセラト"),
    MT("MT", "Malta.", "マルタ共和国"),
    MU("MU", "Mauritius.", "モーリシャス共和国"),
    MV("MV", "Maldives.", "モルディブ共和国"),
    MW("MW", "Malawi.", "マラウイ共和国"),
    MX("MX", "Mexico.", "メキシコ合衆国"),
    MY("MY", "Malaysia.", "マレーシア"),
    MZ("MZ", "Mozambique.", "モザンビーク共和国"),
    NA("NA", "Namibia.", "ナミビア共和国"),
    NC("NC", "New Caledonia.", "フランス領ニューカレドニア"),
    NE("NE", "Niger (the).", "ニジェール共和国"),
    NF("NF", "Norfolk Island.", "オーストラリア領ノーフォーク島"),
    NG("NG", "Nigeria.", "ナイジェリア連邦共和国"),
    NI("NI", "Nicaragua.", "ニカラグア共和国"),
    NL("NL", "Netherlands (the).", "オランダ王国"),
    NO("NO", "Norway.", "ノルウェー王国"),
    NP("NP", "Nepal.", "ネパール連邦民主共和国"),
    NR("NR", "Nauru.", "ナウル共和国"),
    NU("NU", "Niue.", "ニュージーランド領ニウエ"),
    NZ("NZ", "New Zealand.", "ニュージーランド"),
    OM("OM", "Oman.", "オマーン・スルターン国"),
    PA("PA", "Panama.", "パナマ共和国"),
    PE("PE", "Peru.", "ペルー共和国"),
    PF("PF", "French Polynesia.", "フランス領ポリネシア"),
    PG("PG", "Papua New Guinea.", "パプアニューギニア独立国"),
    PH("PH", "Philippines (the).", "フィリピン共和国"),
    PK("PK", "Pakistan.", "パキスタン・イスラム共和国"),
    PL("PL", "Poland.", "ポーランド共和国"),
    PM("PM", "Saint Pierre and Miquelon.", "フランス領サン・ピエール・ミクロン"),
    PN("PN", "Pitcairn.", "ピトケアン諸島"),
    PR("PR", "Puerto Rico.", "アメリカ合衆国プエルトリコ"),
    PS("PS", "Palestine, State of.", "パレスチナ国"),
    PT("PT", "Portugal.", "ポルトガル共和国"),
    PW("PW", "Palau.", "パラオ共和国"),
    PY("PY", "Paraguay.", "パラグアイ共和国"),
    QA("QA", "Qatar.", "カタール国"),
    RE("RE", "Réunion.", "フランス領レユニオン"),
    RO("RO", "Romania.", "ルーマニア"),
    RS("RS", "Serbia.", "セルビア共和国"),
    RU("RU", "Russian Federation (the).", "ロシア連邦"),
    RW("RW", "Rwanda.", "ルワンダ共和国"),
    SA("SA", "Saudi Arabia.", "サウジアラビア王国"),
    SB("SB", "Solomon Islands.", "ソロモン諸島"),
    SC("SC", "Seychelles.", "セーシェル共和国"),
    SD("SD", "Sudan (the).", "スーダン共和国"),
    SE("SE", "Sweden.", "スウェーデン王国"),
    SG("SG", "Singapore.", "シンガポール共和国"),
    SH("SH", "Saint Helena, Ascension and Tristan da Cunha.", "イギリス領セントヘレナ・アセンションおよびトリスタンダクーニャ"),
    SI("SI", "Slovenia.", "スロベニア共和国"),
    SJ("SJ", "Svalbard and Jan Mayen.", "ノルウェー領スヴァールバル諸島およびヤンマイエン島"),
    SK("SK", "Slovakia.", "スロバキア共和国"),
    SL("SL", "Sierra Leone.", "シエラレオネ共和国"),
    SM("SM", "San Marino.", "サンマリノ共和国"),
    SN("SN", "Senegal.", "セネガル共和国"),
    SO("SO", "Somalia.", "ソマリア連邦共和国"),
    SR("SR", "Suriname.", "スリナム共和国"),
    SS("SS", "South Sudan.", "南スーダン共和国"),
    ST("ST", "Sao Tome and Principe.", "サントメ・プリンシペ民主共和国"),
    SV("SV", "El Salvador.", "エルサルバドル共和国"),
    SX("SX", "Sint Maarten (Dutch part).", "オランダ領シント・マールテン"),
    SY("SY", "Syrian Arab Republic (the).", "シリア・アラブ共和国"),
    SZ("SZ", "Eswatini.", "エスワティニ王国"),
    TC("TC", "Turks and Caicos Islands (the).", "イギリス領タークス・カイコス諸島"),
    TD("TD", "Chad.", "チャド共和国"),
    TF("TF", "French Southern Territories (the).", "フランス領南方・南極地域"),
    TG("TG", "Togo.", "トーゴ共和国"),
    TH("TH", "Thailand.", "タイ王国"),
    TJ("TJ", "Tajikistan.", "タジキスタン共和国"),
    TK("TK", "Tokelau.", "ニュージーランド領トケラウ諸島"),
    TL("TL", "Timor-Leste.", "東ティモール民主共和国"),
    TM("TM", "Turkmenistan.", "トルクメニスタン"),
    TN("TN", "Tunisia.", "チュニジア共和国"),
    TO("TO", "Tonga.", "トンガ王国"),
    TR("TR", "Turkey.", "トルコ共和国"),
    TT("TT", "Trinidad and Tobago.", "トリニダード・トバゴ共和国"),
    TV("TV", "Tuvalu.", "ツバル"),
    TW("TW", "Taiwan (Province of China).", "台湾"),
    TZ("TZ", "Tanzania, the United Republic of.", "タンザニア連合共和国"),
    UA("UA", "Ukraine.", "ウクライナ"),
    UG("UG", "Uganda.", "ウガンダ共和国"),
    UM("UM", "United States Minor Outlying Islands (the).", "アメリカ合衆国領有小離島"),
    US("US", "United States of America (the).", "アメリカ合衆国(米国)"),
    UY("UY", "Uruguay.", "ウルグアイ東方共和国"),
    UZ("UZ", "Uzbekistan.", "ウズベキスタン共和国"),
    VA("VA", "Holy See (the).", "バチカン市国"),
    VC("VC", "Saint Vincent and the Grenadines.", "セントビンセントおよびグレナディーン諸島"),
    VE("VE", "Venezuela (Bolivarian Republic of).", "ベネズエラ・ボリバル共和国"),
    VG("VG", "Virgin Islands (British).", "イギリス領ヴァージン諸島"),
    VI("VI", "Virgin Islands (U.S.).", "アメリカ領ヴァージン諸島"),
    VN("VN", "Viet Nam.", "ベトナム社会主義共和国"),
    VU("VU", "Vanuatu.", "バヌアツ共和国"),
    WF("WF", "Wallis and Futuna.", "フランス領ウォリス・フツナ諸島"),
    WS("WS", "Samoa.", "サモア独立国"),
    YE("YE", "Yemen.", "イエメン共和国"),
    YT("YT", "Mayotte.", "フランス領マヨット"),
    ZA("ZA", "South Africa.", "南アフリカ共和国"),
    ZM("ZM", "Zambia.", "ザンビア共和国"),
    ZW("ZW", "Zimbabwe.", "ジンバブウェ共和国");


    CountryCode(String id, String name, String ifaNm) {
        this.id = id;
        this.name = name;
        this.ifaNm = ifaNm;
    }

    private String id;
    private String name;
    private String ifaNm;

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public String getIfaNm() {
        return ifaNm;
    }

    public static CountryCode getById(String id) {
        if (ObjectUtils.isEmpty(id)) {
            return null;
        }

        CountryCode[] enums = values();

        for (int i = 0; i < enums.length; i++) {
            if (enums[i].getId().equals(id)) {
                return enums[i];
            }
        }

        return null;
    }
}
