package com.sbisec.helios.ap.api.athena.enums;

import org.springframework.util.ObjectUtils;

/**
 * 
 * @Description:通貨コード
 * @author shuchen.xin
 * @date: 06/04/2021
 */
public enum CurrencyCode {
    ADP("ADP", "Andorran peseta."),
    AED("AED", "UAE Dirham."),
    AFA("AFA", "Afghan afghani."),
    AFN("AFN", "Afghani."),
    ALL("ALL", "Lek."),
    AMD("AMD", "Armenian Dram."),
    ANG("ANG", "Netherlands Antillean Guilder."),
    AOA("AOA", "Kwanza."),
    ARS("ARS", "Argentine Peso."),
    ATS("ATS", "Latvian lats."),
    AUD("AUD", "Australian Dollar."),
    AWG("AWG", "Aruban Florin."),
    AYM("AYM", "AYM."),
    AZM("AZM", "Azerbaijani manat."),
    AZN("AZN", "Azerbaijan Manat."),
    BAM("BAM", "Convertible Mark."),
    BBD("BBD", "Barbados Dollar."),
    BDT("BDT", "Taka."),
    BEF("BEF", "Belgian franc."),
    BGL("BGL", "Bulgarian lev A/62."),
    BGN("BGN", "Bulgarian Lev."),
    BHD("BHD", "Bahraini Dinar."),
    BIF("BIF", "Burundi Franc."),
    BMD("BMD", "Bermudian Dollar."),
    BND("BND", "Brunei Dollar."),
    BOB("BOB", "Boliviano."),
    BOV("BOV", "Mvdol."),
    BRL("BRL", "Brazilian Real."),
    BSD("BSD", "Bahamian Dollar."),
    BTN("BTN", "Ngultrum."),
    BWP("BWP", "Pula."),
    BYB("BYB", "Belarussian Ruble."),
    BYN("BYN", "Belarusian Ruble."),
    BYR("BYR", "Belarussian ruble."),
    BZD("BZD", "Belize Dollar."),
    CAD("CAD", "Canadian Dollar."),
    CDF("CDF", "Congolese Franc."),
    CHE("CHE", "WIR Euro."),
    CHF("CHF", "Swiss Franc."),
    CHW("CHW", "WIR Franc."),
    CLF("CLF", "Unidad de Fomento."),
    CLP("CLP", "Chilean Peso."),
    CNY("CNY", "Yuan Renminbi."),
    COP("COP", "Colombian Peso."),
    COU("COU", "Unidad de Valor Real."),
    CRC("CRC", "Costa Rican Colon."),
    CSD("CSD", "Serbian dinar."),
    CUC("CUC", "Peso Convertible."),
    CUP("CUP", "Cuban Peso."),
    CVE("CVE", "Cabo Verde Escudo."),
    CYP("CYP", "Cypriot pound."),
    CZK("CZK", "Czech Koruna."),
    DEM("DEM", "German mark."),
    DJF("DJF", "Djibouti Franc."),
    DKK("DKK", "Danish Krone."),
    DOP("DOP", "Dominican Peso."),
    DZD("DZD", "Algerian Dinar."),
    EEK("EEK", "Estonian kroon."),
    EGP("EGP", "Egyptian Pound."),
    ERN("ERN", "Nakfa."),
    ESP("ESP", "Spanish peseta."),
    ETB("ETB", "Ethiopian Birr."),
    EUR("EUR", "Euro."),
    FIM("FIM", "Finnish markka."),
    FJD("FJD", "Fiji Dollar."),
    FKP("FKP", "Falkland Islands Pound."),
    FRF("FRF", "French franc."),
    GBP("GBP", "Pound Sterling."),
    GEL("GEL", "Lari."),
    GHC("GHC", "Ghanaian cedi."),
    GHS("GHS", "Ghana Cedi."),
    GIP("GIP", "Gibraltar Pound."),
    GMD("GMD", "Dalasi."),
    GNF("GNF", "Guinean Franc."),
    GRD("GRD", "Greek drachma."),
    GTQ("GTQ", "Quetzal."),
    GWP("GWP", "Guinea-Bissau peso."),
    GYD("GYD", "Guyana Dollar."),
    HKD("HKD", "Hong Kong Dollar."),
    HNL("HNL", "Lempira."),
    HRK("HRK", "Kuna."),
    HTG("HTG", "Gourde."),
    HUF("HUF", "Forint."),
    IDR("IDR", "Rupiah."),
    IEP("IEP", "Irish pound."),
    ILS("ILS", "New Israeli Sheqel."),
    INR("INR", "Indian Rupee."),
    IQD("IQD", "Iraqi Dinar."),
    IRR("IRR", "Iranian Rial."),
    ISK("ISK", "Iceland Krona."),
    ITL("ITL", "Italian lira."),
    JMD("JMD", "Jamaican Dollar."),
    JOD("JOD", "Jordanian Dinar."),
    JPY("JPY", "Yen."),
    KES("KES", "Kenyan Shilling."),
    KGS("KGS", "Som."),
    KHR("KHR", "Riel."),
    KMF("KMF", "Comorian Franc."),
    KPW("KPW", "North Korean Won."),
    KRW("KRW", "Won."),
    KWD("KWD", "Kuwaiti Dinar."),
    KYD("KYD", "Cayman Islands Dollar."),
    KZT("KZT", "Tenge."),
    LAK("LAK", "Lao Kip."),
    LBP("LBP", "Lebanese Pound."),
    LKR("LKR", "Sri Lanka Rupee."),
    LRD("LRD", "Liberian Dollar."),
    LSL("LSL", "Loti."),
    LTL("LTL", "Lithuanian litas."),
    LUF("LUF", "Luxembourg franc."),
    LVL("LVL", "Latvian lats."),
    LYD("LYD", "Libyan Dinar."),
    MAD("MAD", "Moroccan Dirham."),
    MDL("MDL", "Moldovan Leu."),
    MGA("MGA", "Malagasy Ariary."),
    MGF("MGF", "Malagasy franc."),
    MKD("MKD", "Denar."),
    MMK("MMK", "Kyat."),
    MNT("MNT", "Tugrik."),
    MOP("MOP", "Pataca."),
    MRO("MRO", "Mauritanian ouguiya."),
    MRU("MRU", "Ouguiya."),
    MTL("MTL", "Maltese lira."),
    MUR("MUR", "Mauritius Rupee."),
    MVR("MVR", "Rufiyaa."),
    MWK("MWK", "Malawi Kwacha."),
    MXN("MXN", "Mexican Peso."),
    MXV("MXV", "Mexican Unidad de Inversion (UDI)."),
    MYR("MYR", "Malaysian Ringgit."),
    MZM("MZM", "Mozambican metical."),
    MZN("MZN", "Mozambique Metical."),
    NAD("NAD", "Namibia Dollar."),
    NGN("NGN", "Naira."),
    NIO("NIO", "Cordoba Oro."),
    NLG("NLG", "Netherlands guilder."),
    NOK("NOK", "Norwegian Krone."),
    NPR("NPR", "Nepalese Rupee."),
    NZD("NZD", "New Zealand Dollar."),
    OMR("OMR", "Rial Omani."),
    PAB("PAB", "Balboa."),
    PEN("PEN", "Sol."),
    PGK("PGK", "Kina."),
    PHP("PHP", "Philippine Peso."),
    PKR("PKR", "Pakistan Rupee."),
    PLN("PLN", "Zloty."),
    PTE("PTE", "Portuguese escudo."),
    PYG("PYG", "Guarani."),
    QAR("QAR", "Qatari Rial."),
    ROL("ROL", "Romanian leu A/52."),
    RON("RON", "Romanian Leu."),
    RSD("RSD", "Serbian Dinar."),
    RUB("RUB", "Russian Ruble."),
    RUR("RUR", "Russian rouble A/97."),
    RWF("RWF", "Rwanda Franc."),
    SAR("SAR", "Saudi Riyal."),
    SBD("SBD", "Solomon Islands Dollar."),
    SCR("SCR", "Seychelles Rupee."),
    SDD("SDD", "Sudanese dinar."),
    SDG("SDG", "Sudanese Pound."),
    SEK("SEK", "Swedish Krona."),
    SGD("SGD", "Singapore Dollar."),
    SHP("SHP", "Saint Helena Pound."),
    SIT("SIT", "Slovenian tolar."),
    SKK("SKK", "Slovak koruna."),
    SLL("SLL", "Leone."),
    SOS("SOS", "Somali Shilling."),
    SRD("SRD", "Surinam Dollar."),
    SRG("SRG", "Suriname guilder."),
    SSP("SSP", "South Sudanese Pound."),
    STD("STD", "Sao Tome and Principe dobra."),
    STN("STN", "Dobra."),
    SVC("SVC", "El Salvador Colon."),
    SYP("SYP", "Syrian Pound."),
    SZL("SZL", "Lilangeni."),
    THB("THB", "Baht."),
    TJS("TJS", "Somoni."),
    TMM("TMM", "Turkmenistani manat."),
    TMT("TMT", "Turkmenistan New Manat."),
    TND("TND", "Tunisian Dinar."),
    TOP("TOP", "Pa’anga."),
    TPE("TPE", "Portuguese Timorese escudo."),
    TRL("TRL", "Turkish lira A/05."),
    TRY("TRY", "Turkish Lira."),
    TTD("TTD", "Trinidad and Tobago Dollar."),
    TWD("TWD", "New Taiwan Dollar."),
    TZS("TZS", "Tanzanian Shilling."),
    UAH("UAH", "Hryvnia."),
    UGX("UGX", "Uganda Shilling."),
    USD("USD", "US Dollar."),
    USN("USN", "US Dollar (Next day)."),
    USS("USS", "United States dollar (same day) (funds code)."),
    UYI("UYI", "Uruguay Peso en Unidades Indexadas (UI)."),
    UYU("UYU", "Peso Uruguayo."),
    UYW("UYW", "Unidad Previsional."),
    UZS("UZS", "Uzbekistan Sum."),
    VEB("VEB", "Venezuelan bolivar."),
    VEF("VEF", "Venezuelan bolivar fuerte."),
    VES("VES", "Bolívar Soberano."),
    VND("VND", "Dong."),
    VUV("VUV", "Vatu."),
    WST("WST", "Tala."),
    XAF("XAF", "CFA Franc BEAC."),
    XAG("XAG", "Silver."),
    XAU("XAU", "Gold."),
    XBA("XBA", "Bond Markets Unit European Composite Unit (EURCO)."),
    XBB("XBB", "Bond Markets Unit European Monetary Unit (E.M.U.-6)."),
    XBC("XBC", "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)."),
    XBD("XBD", "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)."),
    XCD("XCD", "East Caribbean Dollar."),
    XDR("XDR", "SDR (Special Drawing Right)."),
    XFO("XFO", "Gold franc (special settlement currency)."),
    XFU("XFU", "UIC franc (special settlement currency)."),
    XOF("XOF", "CFA Franc BCEAO."),
    XPD("XPD", "Palladium."),
    XPF("XPF", "CFP Franc."),
    XPT("XPT", "Platinum."),
    XSU("XSU", "Sucre."),
    XTS("XTS", "Codes specifically reserved for testing purposes."),
    XUA("XUA", "ADB Unit of Account."),
    XXX("XXX", "The codes assigned for athena-service using where no currency is involved."),
    YER("YER", "Yemeni Rial."),
    YUM("YUM", "Yugoslav dinar."),
    ZAR("ZAR", "Rand."),
    ZMK("ZMK", "Zambian kwacha."),
    ZMW("ZMW", "Zambian Kwacha."),
    ZWD("ZWD", "Zimbabwean dollar A/06."),
    ZWL("ZWL", "Zimbabwe Dollar."),
    ZWN("ZWN", "Zimbabwean dollar A/08."),
    ZWR("ZWR", "Zimbabwean dollar A/09.");

    CurrencyCode(String id, String name) {
        this.id = id;
        this.name = name;
    }

    private String id;
    private String name;

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public static CurrencyCode getById(String id) {
        if (ObjectUtils.isEmpty(id)) {
            return null;
        }

        CurrencyCode[] enums = values();

        for (int i = 0; i < enums.length; i++) {
            if (enums[i].getId().equals(id)) {
                return enums[i];
            }
        }

        return null;
    }
}
